GET http://localhost:8080/api/events
###
[
  {
    "_id": "65735bbd48a256bf201f4774",
    "name": "Ithaca Farmers Market",
    "description": "A gathering of local farmers and artisans. Fresh produce, handmade crafts, and more.",
    "date": "2023-07-15",
    "location": "Ithaca Farmers Market Pavilion",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f4775",
    "name": "Cayuga Lake Wine Trail Tour",
    "description": "Explore local wineries around Cayuga Lake with guided tours and tastings.",
    "date": "2023-08-10",
    "location": "Cayuga Lake",
    "headCount": 1
  },
  {
    "_id": "65735bbd48a256bf201f4776",
    "name": "Sciencenter Family Day",
    "description": "A fun day of interactive science activities for children and families.",
    "date": "2023-09-05",
    "location": "Sciencenter",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f4777",
    "name": "Ithaca Festival Parade",
    "description": "Annual parade celebrating the community with music, art, and dance.",
    "date": "2023-06-02",
    "location": "Downtown Ithaca",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f4778",
    "name": "Cornell University Open Lectures",
    "description": "Series of open lectures on various topics by professors and guest speakers.",
    "date": "2023-10-12",
    "location": "Cornell University",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f4779",
    "name": "Ithaca Jazz and Blues Jam",
    "description": "Evening of live jazz and blues performances by local musicians.",
    "date": "2023-07-21",
    "location": "The Haunt",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f477a",
    "name": "Buttermilk Falls Hiking Adventure",
    "description": "Guided hiking tour of the beautiful Buttermilk Falls State Park.",
    "date": "2023-08-18",
    "location": "Buttermilk Falls State Park",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f477b",
    "name": "Downtown Ithaca Food Tour",
    "description": "Culinary tour showcasing the best of Ithaca’s food scene.",
    "date": "2023-09-10",
    "location": "Downtown Ithaca",
    "headCount": 0
  },
  {
    "_id": "65735bbd48a256bf201f477d",
    "name": "Ithaca Art Trail Weekend",
    "description": "Weekend event where local artists open their studios to the public.",
    "date": "2023-10-22",
    "location": "Various locations in Ithaca",
    "headCount": 1
  }
]
###
POST http://localhost:8080/api/events/create
###
{
  "_id": "657360bb78f468cf54987673",
  "name": null,
  "description": null,
  "date": null,
  "location": null,
  "headCount": 0
}
###
DELETE http://localhost:8080/api/events/657360bb78f468cf54987673/delete
###
{
  "message": "Event successfully deleted"
}
###
POST http://localhost:8080/api/events/65735bbd48a256bf201f4777/headCount/rsvp
###
{
  "_id": "65735bbd48a256bf201f4777",
  "name": "Ithaca Festival Parade",
  "description": "Annual parade celebrating the community with music, art, and dance.",
  "date": "2023-06-02",
  "location": "Downtown Ithaca",
  "headCount": 1
}
###
POST http://localhost:8080/api/events/65735bbd48a256bf201f4777/headCount/unrsvp
###
{
  "_id": "65735bbd48a256bf201f4777",
  "name": "Ithaca Festival Parade",
  "description": "Annual parade celebrating the community with music, art, and dance.",
  "date": "2023-06-02",
  "location": "Downtown Ithaca",
  "headCount": 0
}